Repository Opentrons/buildroot, pull requests merged in 2019-09, with the labels that each got.

#37 fix(system): networkmanager.conf: disable auto default for only eth0
  board/opentrons/ot2/rootfs-overlay/etc/NetworkManager/conf.d/disable-autoeth0.conf
Labels: fix, system

#36 fix(system): fix jupyter trash and migrate notebooks
  board/opentrons/ot2/rootfs-overlay/etc/jupyter/jupyter_notebook_config.py
  board/opentrons/ot2/rootfs-overlay/etc/systemd/system/jupyter-notebook.service
  board/opentrons/ot2/rootfs-overlay/etc/systemd/system/jupyter-notebook.service.d/migrate-notebooks.conf
  board/opentrons/ot2/rootfs-overlay/etc/systemd/system/jupyter-notebook.service.d/migrate-notebooks.sh
Labels: fix, system

#39 fix(system): ensure robot button light on after setup
  board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights
Labels: fix, ready-for-review

#38 fix(system): Force journald storage to /var/
  board/opentrons/ot2/rootfs-overlay/etc/systemd/journald.conf.d/log_storage.conf
Labels: fix, system

#40 fix(configs): configs/ot2_defconfig: install regular chardet
  configs/ot2_defconfig
Labels: fix, system

#41 fix(system): make mounts public, add tc bootloader symlink
  board/opentrons/ot2/rootfs-overlay/etc/systemd/system/systemd-udevd.service.d/public-mounts.conf
  board/opentrons/ot2/rootfs-overlay/etc/usbmount/mount.d/01_create_tc_bootloader_symlink
  board/opentrons/ot2/rootfs-overlay/etc/usbmount/umount.d/01_remove_tc_bootloader_symlink
Labels: fix, ready-for-review

#42 fix(system): opentrons/ot2: make wired connections use static macs
  board/opentrons/ot2/rootfs-overlay/usr/share/default-connections/wired
  board/opentrons/ot2/rootfs-overlay/usr/share/default-connections/wired-linklocal
Labels: fix, ready-for-review, system
