Repository Opentrons/buildroot, pull requests merged in 2019-11, with the labels that each got.

#46 python-aionotify: new package
  package/Config.in
  package/python-aionotify/Config.in
  package/python-aionotify/python-aionotify.hash
  package/python-aionotify/python-aionotify.mk
Labels: system

#47 feat(system): configs/ot2_defconfig: select aionotify
  configs/ot2_defconfig
Labels: build

#48 fix: board/opentrons/ot2: strip newlines in syslog upstreaming
  board/opentrons/ot2/rootfs-overlay/etc/syslog-ng.conf
Labels: fix, system

#53 board/opentrons/ot2: always sign builds if key is available
  board/opentrons/ot2/post-image.sh
Labels: build, refactor

#54 board/opentrons/ot2: only remove signing cert if build is unsigned
  board/opentrons/ot2/post-build.sh
Labels: build

#55 boards/opentrons/ot2: journald conf: sync faster
  board/opentrons/ot2/rootfs-overlay/etc/systemd/journald.conf.d/log_storage.conf
Labels: services

#50 remove unused uf2 bootloader support as usb mass storage device
  board/opentrons/ot2/rootfs-overlay/etc/systemd/system/systemd-udevd.service.d/public-mounts.conf
  board/opentrons/ot2/rootfs-overlay/etc/usbmount/mount.d/01_create_tc_bootloader_symlink
  board/opentrons/ot2/rootfs-overlay/etc/usbmount/umount.d/01_remove_tc_bootloader_symlink
Labels: system

#56 Add top level module symlinks
  board/opentrons/ot2/rootfs-overlay/etc/udev/rules.d/95-opentrons-modules.rules
Labels: build
