Repository Opentrons/buildroot, pull requests merged in 2020-09, with the labels that each got.

#102 configs/ot2_defconfig: select screen, python3_curses, tmux
  configs/ot2_defconfig
Labels: cpx, feature, packages, ready-for-review

#103 readme: flesh out build and flash instructions
  README.md
Labels: cpx, docs, ready-for-review

#86 configs/ot2_defconfig: select ca-certificates, curl, git, grep, sl, wget
  configs/ot2_defconfig
Labels: cpx, packages, ready-for-review
