Repository Opentrons/buildroot, pull requests merged in 2022-08, with the labels that each got.

#163 feat(heater-shaker): update firmware version
  package/opentrons/opentrons-heater-shaker-firmware/opentrons-heater-shaker-firmware.hash
  package/opentrons/opentrons-heater-shaker-firmware/opentrons-heater-shaker-firmware.mk
Labels: ready-for-review

#164 board/opentrons/ot2: Work around RV-3028 problems via artificial delay
  board/opentrons/ot2/kernel-patches/0008-Work-around-rv3028-problems-via-artificial-delay.patch
Labels: system

#167 chore(heater-shaker): update heater-shaker firmware version
  package/opentrons/opentrons-heater-shaker-firmware/opentrons-heater-shaker-firmware.hash
  package/opentrons/opentrons-heater-shaker-firmware/opentrons-heater-shaker-firmware.mk
Labels: updates, ready-for-review, packages
